3rd task - 01 createGetter
js-tasks-ru/js-20210806_nadezhda92 pull request #4
Opened 2021-08-18 09:44 UTC by NB1208

2021-08-18 09:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-19 16:21 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const arr = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-08-19 16:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      if (!currRes.hasOwnProperty(item)) {
👍 лайк за использование `hasOwnProperty`

2021-08-19 16:22 UTC, dosandk requested changes
решение `createGetter` следует поправить

2021-08-19 18:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-20 13:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  constructor(data = []) {
проверьте пожалуйста, а какие еще аргументы кроме `data` принимает компонент

2021-08-20 13:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    let html = `<div class="column-chart" style="--chart-height: 50">`
в шаблонных строках нет необходимости использовать оператор `+`

2021-08-20 13:59 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +          <div class="${this.data.data && this.data.data.length ? 'wrapper' : 'column-chart_loading'}">
а почему данная обертка не часть переменной `html`? 
Ведь можно структурировать код вот таким образом:
```
element.innerHTML = html
```

2021-08-20 13:59 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    let html = `<div class="column-chart" style="--chart-height: 50">`
проверьте, а точно `let`? может `const`?

2021-08-20 14:00 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      const res = this.data.data
👍  лайк за использование `map`

2021-08-20 14:00 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +// const columnChart = new ColumnChart();
пожалуйста не оставляйте закомментированный код в PR

2021-08-20 14:01 UTC, dosandk requested changes
проверьте пожалуйста аргументы `ColumnChart`

2021-08-20 14:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-20 17:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-22 10:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-23 22:10 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    Object.assign(this, {duration: 1000, type: 'success'}, params);
да, через `Object.assign` можно расширить значения `this` но на практике так делать я не рекомендую. 
Такой подход сокращает количество кода, но оставляет без ответа вопрос, а что же находится в `params`

2021-08-23 22:13 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (window.notifications && window.notifications.length) {
Вы двигались в правильно направлении, но есть несколько моментов, когда мы присваиваем что-то в `windows` - мы делаем это значение глобальным (доступным для всех других скриптов на странице). Это не очень хорошая практика, ведь может произойти конфликт имен или какой-то скрипт неумышленно перетрет  значение в поле `window.notification` 
Поэтому следует подумать, может лучше объявить переменную `let` прямо в данном файле, до объявления класса, или воспользоваться статическим свойством

2021-08-23 22:14 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    window.notifications = [this];
нам не нужен целый массив, достаточно сохранить ссылку на предыдущий нотификейшен

2021-08-23 22:14 UTC, dosandk approved these changes
решение принято, но посмотрите пожалуйста комментарий

2021-08-23 22:15 UTC, merged